# Generated by Django 5.0 on 2023-12-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author_name', models.CharField(max_length=100)),
                ('author_bio', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='article_images/')),
                ('link', models.URLField(blank=True)),
                ('text', models.TextField()),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
