# Generated by Django 5.0 on 2023-12-08 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_back', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author_bio',
        ),
    ]
